/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Store;

import hany.*;
import java.awt.ComponentOrientation;
import java.awt.HeadlessException;
import java.awt.Image;
import java.io.ByteArrayOutputStream;
import java.io.File;
import java.io.FileInputStream;
import java.io.IOException;
import java.io.InputStream;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableCellRenderer;
import net.sf.jasperreports.engine.JRException;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.view.JasperViewer;
import org.jdesktop.swingx.autocomplete.AutoCompleteDecorator;
import java.util.HashMap;
import java.util.Locale;
import java.util.Map;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author amnassar
 */
public final class storeitemfollow extends javax.swing.JInternalFrame {

    /**
     * Creates new form book
     */
     
    PreparedStatement pst;
    ResultSet rs;
    public String y;

    public storeitemfollow() {
        initComponents();
         
        clear();
        tablelord();
        category();
        name.setComponentOrientation(ComponentOrientation.RIGHT_TO_LEFT);
        AutoCompleteDecorator.decorate(cmcategory);
        TableCellRenderer rendererFromHeader = tdetails.getTableHeader().getDefaultRenderer();
        JLabel headerLabel = (JLabel) rendererFromHeader;
        headerLabel.setHorizontalAlignment(JLabel.CENTER);
        DefaultTableCellRenderer centerRenderer = new DefaultTableCellRenderer();
        centerRenderer.setHorizontalAlignment(JLabel.CENTER);
        tdetails.getColumnModel().getColumn(0).setCellRenderer(centerRenderer);
        tdetails.getColumnModel().getColumn(1).setCellRenderer(centerRenderer);
        tdetails.getColumnModel().getColumn(2).setCellRenderer(centerRenderer);
        tdetails.getColumnModel().getColumn(3).setCellRenderer(centerRenderer);
        tdetails.getColumnModel().getColumn(4).setCellRenderer(centerRenderer);
        tdetails.getColumnModel().getColumn(5).setCellRenderer(centerRenderer);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel16 = new javax.swing.JLabel();
        jPanel10 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tdetails = new javax.swing.JTable();
        jLabel14 = new javax.swing.JLabel();
        number = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        name = new javax.swing.JTextField();
        code = new javax.swing.JTextField();
        save3 = new javax.swing.JButton();
        jLabel32 = new javax.swing.JLabel();
        cmcategory = new javax.swing.JComboBox();
        save2 = new javax.swing.JButton();
        save1 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        serialid = new javax.swing.JLabel();

        jLabel16.setFont(new java.awt.Font("Sitka Text", 3, 24)); // NOI18N
        jLabel16.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/71847608-close-up-of-handshake-on-city-background-with-abstract-sunlight-partnership-concept-double-exposure.jpg"))); // NOI18N

        setMaximumSize(new java.awt.Dimension(980, 690));
        setMinimumSize(new java.awt.Dimension(980, 690));
        setPreferredSize(new java.awt.Dimension(980, 690));

        jPanel10.setBackground(new java.awt.Color(0, 0, 0));
        jPanel10.setForeground(new java.awt.Color(255, 255, 255));
        jPanel10.setMinimumSize(new java.awt.Dimension(90, 34));
        jPanel10.setPreferredSize(new java.awt.Dimension(970, 690));
        jPanel10.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tdetails.setBackground(new java.awt.Color(156, 166, 187));
        tdetails.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        tdetails.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "سعر الجمهور", "سعر البيع", "العدد", "المخزن", "اسم المنتج", "الكود"
            }
        ));
        tdetails.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        tdetails.setRowHeight(25);
        tdetails.setRowMargin(2);
        tdetails.setSelectionBackground(new java.awt.Color(204, 255, 255));
        tdetails.setSelectionForeground(new java.awt.Color(0, 0, 0));
        tdetails.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tdetailsMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tdetails);
        if (tdetails.getColumnModel().getColumnCount() > 0) {
            tdetails.getColumnModel().getColumn(0).setMinWidth(100);
            tdetails.getColumnModel().getColumn(0).setPreferredWidth(100);
            tdetails.getColumnModel().getColumn(0).setMaxWidth(100);
            tdetails.getColumnModel().getColumn(1).setMinWidth(100);
            tdetails.getColumnModel().getColumn(1).setPreferredWidth(100);
            tdetails.getColumnModel().getColumn(1).setMaxWidth(100);
            tdetails.getColumnModel().getColumn(2).setMinWidth(100);
            tdetails.getColumnModel().getColumn(2).setPreferredWidth(100);
            tdetails.getColumnModel().getColumn(2).setMaxWidth(100);
            tdetails.getColumnModel().getColumn(5).setMinWidth(120);
            tdetails.getColumnModel().getColumn(5).setPreferredWidth(120);
            tdetails.getColumnModel().getColumn(5).setMaxWidth(120);
        }

        jPanel10.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 280, 920, 280));

        jLabel14.setBackground(new java.awt.Color(255, 255, 255));
        jLabel14.setFont(new java.awt.Font("Arial", 1, 30)); // NOI18N
        jLabel14.setText("العدد");
        jPanel10.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 180, 80, 30));

        number.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jPanel10.add(number, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 180, 190, 30));

        jLabel13.setBackground(new java.awt.Color(255, 255, 255));
        jLabel13.setFont(new java.awt.Font("Arial", 1, 30)); // NOI18N
        jLabel13.setText("المنتج");
        jPanel10.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 30, -1, -1));

        jLabel12.setBackground(new java.awt.Color(255, 255, 255));
        jLabel12.setFont(new java.awt.Font("Arial", 1, 30)); // NOI18N
        jLabel12.setText("الكود");
        jPanel10.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 130, 80, 30));

        name.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jPanel10.add(name, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 30, 190, 30));

        code.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jPanel10.add(code, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 130, 190, 30));

        save3.setBackground(new java.awt.Color(156, 166, 187));
        save3.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        save3.setText("تقرير");
        save3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                save3ActionPerformed(evt);
            }
        });
        jPanel10.add(save3, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 80, 150, 60));

        jLabel32.setBackground(new java.awt.Color(255, 255, 255));
        jLabel32.setFont(new java.awt.Font("Arial", 1, 30)); // NOI18N
        jLabel32.setText("المخزن");
        jPanel10.add(jLabel32, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 80, 80, -1));

        cmcategory.setEditable(true);
        jPanel10.add(cmcategory, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 80, 190, 30));

        save2.setBackground(new java.awt.Color(156, 166, 187));
        save2.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        save2.setText("تفريغ");
        save2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                save2ActionPerformed(evt);
            }
        });
        jPanel10.add(save2, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 230, 180, 40));

        save1.setBackground(new java.awt.Color(156, 166, 187));
        save1.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        save1.setText("بحث");
        save1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                save1ActionPerformed(evt);
            }
        });
        jPanel10.add(save1, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 230, 180, 40));

        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/nYwGq3.jpg"))); // NOI18N
        jLabel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 0, 0), 2));
        jPanel10.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 970, 720));

        serialid.setText("jLabel1");
        jPanel10.add(serialid, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 650, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel10, javax.swing.GroupLayout.DEFAULT_SIZE, 964, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel10, javax.swing.GroupLayout.DEFAULT_SIZE, 637, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void save1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_save1ActionPerformed

        String namee = name.getText();
        String codee = code.getText();
        String numberr = number.getText();
        String category = cmcategory.getSelectedItem().toString();

        try {
            String sqll = "SELECT sell,buy,number,category,name,serial FROM battry.storeitem WHERE  1=1 ";
            if (!name.getText().trim().isEmpty()) {
                sqll = sqll + " AND name LIKE '%" + namee + "%'";
            } else if (!code.getText().trim().isEmpty()) {
                sqll = sqll + " AND serial LIKE '%" + codee + "%'";
            } else if (!number.getText().trim().isEmpty()) {
                sqll = sqll + " AND number LIKE '%" + numberr + "%'";
            } else if (!cmcategory.getSelectedItem().toString().trim().isEmpty()) {
                sqll = sqll + " AND category LIKE '%" + cmcategory.getSelectedItem().toString() + "%'";
            }

            pst = (PreparedStatement) DBConnect.con.prepareStatement(sqll);
            rs = pst.executeQuery();
            DefaultTableModel model = (DefaultTableModel) tdetails.getModel();
            model.setRowCount(0);
            int k = 0;
            while (rs.next()) {
                Object row[] = {
                    rs.getString("sell"),
                    rs.getString("buy"),
                    rs.getString("number"),
                    rs.getString("category"),
                    rs.getString("name"),
                    rs.getString("serial"),};
                model.addRow(row);
                k++;
            }
            for (int i = k; i < 11; i++) {
                Object rowData[] = {
                    "",
                    "",
                    "",
                    "",
                    "",};
                model.addRow(rowData);
            }
        } catch (SQLException ex) {
        }
    }//GEN-LAST:event_save1ActionPerformed

    private void save2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_save2ActionPerformed
        clear();
        tablelord();
    }//GEN-LAST:event_save2ActionPerformed

    private void save3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_save3ActionPerformed

        /* if(name.getText().trim().isEmpty())
         {
         JOptionPane.showMessageDialog(rootPane, "اختر العميل");
         }
         else
         {
         InputStream in=null;
         try {
         String namee =name.getText().toString() ;

         String reportpath= "\\\\192.168.1.15\\sadam\\cart.jasper";
         Map<String,Object> para = new HashMap<String,Object>();
         para.put("name", namee);
         JasperPrint j = JasperFillManager.fillReport(reportpath, para,con);
         JasperViewer.viewReport(j,false);
         }
         catch (JRException ex) {
         JOptionPane.showMessageDialog(null,ex);
         } finally {

         }}*/
    }//GEN-LAST:event_save3ActionPerformed

    private void tdetailsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tdetailsMouseClicked
        DefaultTableModel tmodel = (DefaultTableModel) tdetails.getModel();
        //bid,name, price, publisher, book_type, b_code, date, category
        int selectrowindex = tdetails.getSelectedRow();
        name.setText(tmodel.getValueAt(selectrowindex, 4).toString());
        code.setText(tmodel.getValueAt(selectrowindex, 5).toString());
        number.setText(tmodel.getValueAt(selectrowindex, 2).toString());
        cmcategory.setSelectedItem(tmodel.getValueAt(selectrowindex, 3).toString());


    }//GEN-LAST:event_tdetailsMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox cmcategory;
    private javax.swing.JTextField code;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField name;
    private javax.swing.JTextField number;
    private javax.swing.JButton save1;
    private javax.swing.JButton save2;
    private javax.swing.JButton save3;
    private javax.swing.JLabel serialid;
    private javax.swing.JTable tdetails;
    // End of variables declaration//GEN-END:variables
public void clear() {
        name.setText("");
        code.setText("");
        number.setText("");
        serialid.setText("");

    }

    public void tablelord() {
        try {
            String sqll = "SELECT sell,buy,number,category,name,serial FROM battry.storeitem";
            pst = (PreparedStatement) DBConnect.con.prepareStatement(sqll);
            rs = pst.executeQuery();
            DefaultTableModel model = (DefaultTableModel) tdetails.getModel();
            model.setRowCount(0);
            int k = 0;
            while (rs.next()) {
                Object row[] = {
                    rs.getString("sell"),
                    rs.getString("buy"),
                    rs.getString("number"),
                    rs.getString("category"),
                    rs.getString("name"),
                    rs.getString("serial"),};
                model.addRow(row);
                k++;
            }
            for (int i = k; i < 11; i++) {
                Object rowData[] = {
                    "",
                    "",
                    "",
                    "",
                    "",
                    "",
                    "",
                    "",
                    "",};
                model.addRow(rowData);
            }
        } catch (SQLException ex) {

        }
    }

    public void category() {
        try {
            String sql = "SELECT name  FROM battry.storecategory order by name ";
            pst = (PreparedStatement) DBConnect.con.prepareStatement(sql);
            rs = pst.executeQuery();
            while (rs.next()) {
                String name = rs.getString("name");

                cmcategory.addItem(name);

            }

        } catch (SQLException ex) {

        }
    }

}
