/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package hany;

import java.awt.Color;
import java.awt.ComponentOrientation;
import java.awt.Font;
import java.awt.HeadlessException;
import java.awt.Image;
import java.io.ByteArrayOutputStream;
import java.io.File;
import java.io.FileInputStream;
import java.io.IOException;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.Calendar;
import java.util.GregorianCalendar;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JScrollPane;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.JTableHeader;
import javax.swing.table.TableCellRenderer;

/**
 *
 * @author amnassar
 */
public final class additems extends javax.swing.JInternalFrame {

    /**
     * Creates new form book
     */
     
    PreparedStatement pst;
    ResultSet rs;
    public String y;
    int day;
    int month;
    int year;

    public additems() {
        initComponents();
         
        tablelord();
        types();
        clear();

        Calendar cal = new GregorianCalendar();
        day = cal.get(Calendar.DAY_OF_MONTH);
        month = cal.get(Calendar.MONTH) + 1;
        year = cal.get(Calendar.YEAR);
        name.setComponentOrientation(ComponentOrientation.RIGHT_TO_LEFT);
        TableCellRenderer rendererFromHeader = jTable1.getTableHeader().getDefaultRenderer();
        JLabel headerLabel = (JLabel) rendererFromHeader;
        headerLabel.setHorizontalAlignment(JLabel.CENTER);
        DefaultTableCellRenderer centerRenderer = new DefaultTableCellRenderer();
        centerRenderer.setHorizontalAlignment(JLabel.CENTER);
        jTable1.getColumnModel().getColumn(0).setCellRenderer(centerRenderer);
        jTable1.getColumnModel().getColumn(1).setCellRenderer(centerRenderer);
        jTable1.getColumnModel().getColumn(2).setCellRenderer(centerRenderer);
        jTable1.getColumnModel().getColumn(3).setCellRenderer(centerRenderer);
        jTable1.getColumnModel().getColumn(4).setCellRenderer(centerRenderer);
        jTable1.getColumnModel().getColumn(5).setCellRenderer(centerRenderer);
        jTable1.getColumnModel().getColumn(6).setCellRenderer(centerRenderer);
        jTable1.getTableHeader().setFont(new Font("Arial", Font.BOLD, 20));
        jTable1.getTableHeader().setOpaque(false);
        jTable1.getTableHeader().setBackground(new Color(138, 203, 195));
        jTable1.getTableHeader().setForeground(new Color(0, 0, 0));
        jTable1.setRowHeight(40);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel16 = new javax.swing.JLabel();
        jPanel14 = new javax.swing.JPanel();
        cmtype = new javax.swing.JComboBox();
        jLabel18 = new javax.swing.JLabel();
        khtat = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        name = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        autoserial4 = new javax.swing.JLabel();
        delete4 = new javax.swing.JButton();
        jLabel15 = new javax.swing.JLabel();
        save5 = new javax.swing.JButton();
        save6 = new javax.swing.JButton();
        save4 = new javax.swing.JButton();
        jLabel19 = new javax.swing.JLabel();
        customer = new javax.swing.JTextField();
        jLabel20 = new javax.swing.JLabel();
        studio = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        serialid4 = new javax.swing.JLabel();
        date4 = new javax.swing.JLabel();

        jLabel16.setFont(new java.awt.Font("Sitka Text", 3, 24)); // NOI18N
        jLabel16.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/71847608-close-up-of-handshake-on-city-background-with-abstract-sunlight-partnership-concept-double-exposure.jpg"))); // NOI18N

        setMaximumSize(new java.awt.Dimension(1050, 730));
        setMinimumSize(new java.awt.Dimension(1050, 730));
        setPreferredSize(new java.awt.Dimension(1050, 730));

        jPanel14.setBackground(new java.awt.Color(0, 0, 0));
        jPanel14.setForeground(new java.awt.Color(255, 255, 255));
        jPanel14.setMaximumSize(new java.awt.Dimension(1050, 730));
        jPanel14.setMinimumSize(new java.awt.Dimension(1050, 730));
        jPanel14.setPreferredSize(new java.awt.Dimension(1050, 730));
        jPanel14.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        cmtype.setEditable(true);
        cmtype.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        cmtype.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "-" }));
        cmtype.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cmtypeMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                cmtypeMouseEntered(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                cmtypeMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                cmtypeMouseReleased(evt);
            }
        });
        cmtype.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmtypeActionPerformed(evt);
            }
        });
        cmtype.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                cmtypeKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                cmtypeKeyReleased(evt);
            }
        });
        jPanel14.add(cmtype, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 110, 190, 30));

        jLabel18.setBackground(new java.awt.Color(255, 255, 255));
        jLabel18.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jLabel18.setText("سعر الخطاط");
        jPanel14.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 160, 140, 30));

        khtat.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        khtat.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jPanel14.add(khtat, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 160, 80, 30));

        jScrollPane1.setBackground(new java.awt.Color(204, 255, 255));
        jScrollPane1.setForeground(new java.awt.Color(204, 255, 255));

        jTable1.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "عدد", "الاستوديو", "العميل", "الخطاط", "النوع", "الاسم", "id"
            }
        ));
        jTable1.setFocusable(false);
        jTable1.setIntercellSpacing(new java.awt.Dimension(0, 0));
        jTable1.setRowHeight(25);
        jTable1.setSelectionBackground(new java.awt.Color(204, 255, 255));
        jTable1.setShowVerticalLines(false);
        jTable1.getTableHeader().setReorderingAllowed(false);
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);
        if (jTable1.getColumnModel().getColumnCount() > 0) {
            jTable1.getColumnModel().getColumn(6).setMinWidth(1);
            jTable1.getColumnModel().getColumn(6).setPreferredWidth(1);
            jTable1.getColumnModel().getColumn(6).setMaxWidth(1);
        }

        jPanel14.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 300, 880, 310));

        name.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jPanel14.add(name, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 60, 190, 30));

        jLabel17.setBackground(new java.awt.Color(255, 255, 255));
        jLabel17.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jLabel17.setText("اسم المنتج");
        jPanel14.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 60, 140, 30));

        autoserial4.setFont(new java.awt.Font("Tahoma", 3, 18)); // NOI18N
        autoserial4.setForeground(new java.awt.Color(255, 255, 255));
        autoserial4.setText("لإثسف");
        jPanel14.add(autoserial4, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 10, 170, 60));

        delete4.setBackground(new java.awt.Color(138, 203, 195));
        delete4.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        delete4.setText("مسح");
        delete4.setEnabled(false);
        delete4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                delete4ActionPerformed(evt);
            }
        });
        jPanel14.add(delete4, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 630, 120, 40));

        jLabel15.setBackground(new java.awt.Color(255, 255, 255));
        jLabel15.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jLabel15.setText("نوع المنتج");
        jPanel14.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 110, 140, 30));

        save5.setBackground(new java.awt.Color(138, 203, 195));
        save5.setFont(new java.awt.Font("Arial", 1, 30)); // NOI18N
        save5.setText("بحث");
        save5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                save5ActionPerformed(evt);
            }
        });
        jPanel14.add(save5, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 230, 110, 40));

        save6.setBackground(new java.awt.Color(138, 203, 195));
        save6.setFont(new java.awt.Font("Arial", 1, 30)); // NOI18N
        save6.setText("تفريغ");
        save6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                save6ActionPerformed(evt);
            }
        });
        jPanel14.add(save6, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 230, 110, 40));

        save4.setBackground(new java.awt.Color(138, 203, 195));
        save4.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        save4.setText("حفظ");
        save4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                save4ActionPerformed(evt);
            }
        });
        jPanel14.add(save4, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 230, 120, 40));

        jLabel19.setBackground(new java.awt.Color(255, 255, 255));
        jLabel19.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jLabel19.setText("سعر العميل");
        jPanel14.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 160, 140, 30));

        customer.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        customer.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jPanel14.add(customer, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 160, 80, 30));

        jLabel20.setBackground(new java.awt.Color(255, 255, 255));
        jLabel20.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jLabel20.setText("سعر استوديو");
        jPanel14.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 160, 130, 30));

        studio.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        studio.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jPanel14.add(studio, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 160, 80, 30));

        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/nYwGq3.jpg"))); // NOI18N
        jLabel6.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 0, 0), 2));
        jPanel14.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1050, 730));

        serialid4.setText("jLabel1");
        jPanel14.add(serialid4, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 650, -1, -1));

        date4.setText("jLabel1");
        jPanel14.add(date4, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 170, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1050, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jPanel14, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 730, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jPanel14, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void delete4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_delete4ActionPerformed
        if (serialid4.getText().trim().isEmpty()) {
            JOptionPane.showMessageDialog(rootPane, "اختر المنتج المراد مسحة");

        } else {
            int dialogButton = JOptionPane.YES_NO_OPTION;
            int dialogResult = JOptionPane.showConfirmDialog(this, "حفظ العملية ؟", "رسالة تاكيد ", dialogButton);
            if (dialogResult == 0) {
                try {
                    String sql = "DELETE FROM battry.items WHERE id='" + serialid4.getText() + "'";
                    pst = (PreparedStatement) DBConnect.con.prepareStatement(sql);
                    pst.execute();
                    JOptionPane.showMessageDialog(rootPane, " تم مسح المنتج بنجاح");
                    tablelord();
                    clear();
                } catch (SQLException ex) {

                }
                clear();
            } else {

                JOptionPane.showMessageDialog(this, "الغاء العملية ");
            }
        }
    }//GEN-LAST:event_delete4ActionPerformed

    private void save4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_save4ActionPerformed
        try {
            float customerprice = Float.parseFloat(customer.getText());
            float khtatprice = Float.parseFloat(khtat.getText());
            float studioprice = Float.parseFloat(studio.getText());
            String namee = name.getText();
            String type = cmtype.getSelectedItem().toString();
            if (serialid4.getText().trim().isEmpty()) {

                if (name.getText().trim().isEmpty() || khtat.getText().trim().isEmpty() || studio.getText().trim().isEmpty() || customer.getText().trim().isEmpty()) {
                    JOptionPane.showMessageDialog(this, " من فضلك اكمل البيانات ");
                } else {
                    int dialogButton = JOptionPane.YES_NO_OPTION;
                    int dialogResult = JOptionPane.showConfirmDialog(this, "حفظ العملية ؟", "رسالة تاكيد ", dialogButton);
                    if (dialogResult == 0) {
                        try {
                            String sql = "INSERT INTO battry.items (name,type,customerprice,khtatprice,studioprice) VALUES"
                                    + " ('" + namee + "','" + type + "','" + customerprice + "','" + khtatprice + "','" + studioprice + "')";
                            pst = (PreparedStatement) DBConnect.con.prepareStatement(sql);
                            pst.execute();
                            JOptionPane.showMessageDialog(null, "تم اضافة المنتج بنجاح");
                            tablelord();
                            clear();
                        } catch (Exception e) {
                            JOptionPane.showMessageDialog(null, "المنتج مضاف من قبل");
                        }

                    } else {
                        JOptionPane.showMessageDialog(this, "الغاء العملية");

                    }
                }
            } else {
                String sqla = "UPDATE battry.items SET name='" + namee + "',type='" + type + "',customerprice='" + customerprice + "',khtatprice='" + khtatprice + "',studioprice='" + studioprice + "' where id = '" + serialid4.getText() + "'";
                pst = (PreparedStatement) DBConnect.con.prepareStatement(sqla);
                pst.executeUpdate();
                JOptionPane.showMessageDialog(this, "تم التعديل علي المنتج");
                tablelord();
                clear();
                name.requestFocus();
            }

        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "الاسعار غير صحيحة");
        }
    }//GEN-LAST:event_save4ActionPerformed

    private void cmtypeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cmtypeMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_cmtypeMouseClicked

    private void cmtypeMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cmtypeMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_cmtypeMouseEntered

    private void cmtypeMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cmtypeMousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmtypeMousePressed

    private void cmtypeMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cmtypeMouseReleased

    }//GEN-LAST:event_cmtypeMouseReleased

    private void cmtypeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmtypeActionPerformed

    }//GEN-LAST:event_cmtypeActionPerformed

    private void cmtypeKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_cmtypeKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmtypeKeyPressed

    private void cmtypeKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_cmtypeKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_cmtypeKeyReleased

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        DefaultTableModel tmodel = (DefaultTableModel) jTable1.getModel();
        int selectrowindex = jTable1.getSelectedRow();
        serialid4.setText(tmodel.getValueAt(selectrowindex, 6).toString());
        name.setText(tmodel.getValueAt(selectrowindex, 5).toString());
        khtat.setText(tmodel.getValueAt(selectrowindex, 3).toString());
        studio.setText(tmodel.getValueAt(selectrowindex, 1).toString());
        cmtype.setSelectedItem(tmodel.getValueAt(selectrowindex, 4).toString());
        customer.setText(tmodel.getValueAt(selectrowindex, 2).toString());

    }//GEN-LAST:event_jTable1MouseClicked

    private void save5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_save5ActionPerformed
        try {
            String namee = name.getText();
            String typee = cmtype.getSelectedItem().toString();

            String sqll = "SELECT * FROM battry.items WHERE  1=1 ";
            if (!name.getText().trim().isEmpty()) {
                sqll = sqll + " AND name LIKE '%" + namee + "%'";
            }
            if (!cmtype.getSelectedItem().toString().trim().isEmpty()) {
                sqll = sqll + " AND type LIKE '%" + typee + "%'";
            }

            pst = (PreparedStatement) DBConnect.con.prepareStatement(sqll);
            rs = pst.executeQuery();
            DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
            model.setRowCount(0);
            int k = 0;
            while (rs.next()) {
                Object row[] = {
                    rs.getString("number"),
                    rs.getString("studioprice"),
                    rs.getString("customerprice"),
                    rs.getString("khtatprice"),
                    rs.getString("type"),
                    rs.getString("name"),
                    rs.getString("id"),};
                model.addRow(row);
                k++;
            }
            for (int i = k; i < 11; i++) {
                Object rowData[] = {
                    "",
                    "",
                    "",
                    "",
                    "",
                    "",
                    "",
                    "",
                    "",
                    "",
                    "",
                    "",};
                model.addRow(rowData);
            }
        } catch (SQLException ex) {
        }
    }//GEN-LAST:event_save5ActionPerformed

    private void save6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_save6ActionPerformed
        clear();
        tablelord();
    }//GEN-LAST:event_save6ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel autoserial4;
    private javax.swing.JComboBox cmtype;
    private javax.swing.JTextField customer;
    private javax.swing.JLabel date4;
    private javax.swing.JButton delete4;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel14;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField khtat;
    private javax.swing.JTextField name;
    private javax.swing.JButton save4;
    private javax.swing.JButton save5;
    private javax.swing.JButton save6;
    private javax.swing.JLabel serialid4;
    private javax.swing.JTextField studio;
    // End of variables declaration//GEN-END:variables

    public void tablelord() {
        try {
            String sqll = "SELECT * FROM battry.items";
            pst = (PreparedStatement) DBConnect.con.prepareStatement(sqll);
            rs = pst.executeQuery();
            DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
            model.setRowCount(0);
            int x = 1;
            while (rs.next()) {
                Object row[] = {
                    rs.getString("number"),
                    rs.getString("studioprice"),
                    rs.getString("customerprice"),
                    rs.getString("khtatprice"),
                    rs.getString("type"),
                    rs.getString("name"),
                    rs.getString("id"),};
                model.addRow(row);
                x++;

            }
            if (x >= 11) {
            } else {
                for (int z = x; z < 13; z++) {
                    Object rowData[] = {
                        "", "", "", "", "",};
                    model.addRow(rowData);
                }
            }
        } catch (SQLException ex) {

        }
    }

    public void clear() {
        name.setText("");
        khtat.setText("");
        customer.setText("");
        studio.setText("");
        serialid4.setText("");
    }

    public void types() {
        try {
            String sql = "SELECT name  FROM battry.itemtype order by id";
            pst = (PreparedStatement) DBConnect.con.prepareStatement(sql);
            rs = pst.executeQuery();
            while (rs.next()) {
                String namee = rs.getString("name");

                cmtype.addItem(namee);

            }

        } catch (SQLException ex) {

        }
    }

}
