/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package hany;

import java.awt.ComponentOrientation;
import java.awt.event.ItemEvent;
import java.awt.event.ItemListener;
import java.awt.event.KeyEvent;
import java.io.File;
import java.io.IOException;
import java.io.InputStream;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.Calendar;
import java.util.GregorianCalendar;
import java.util.HashMap;
import java.util.Map;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JComboBox;
import javax.swing.JOptionPane;
import net.sf.jasperreports.engine.JRException;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.JasperPrintManager;
import net.sf.jasperreports.view.JasperViewer;
import org.jdesktop.swingx.autocomplete.AutoCompleteDecorator;

/**
 *
 * @author amnassar
 */
public class sizee extends javax.swing.JFrame {

    public String LL = null;
    PreparedStatement pst;
    Home h;
    ResultSet rs;
    String dayyy;

    public sizee() {
        initComponents();
     
       

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        save1 = new javax.swing.JButton();
        total = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        thderhight = new javax.swing.JTextField();
        thderwidth = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        wantedhight = new javax.swing.JTextField();
        wantedwidth = new javax.swing.JTextField();
        resultwidth = new javax.swing.JTextField();
        save = new javax.swing.JButton();
        allhight = new javax.swing.JTextField();
        allwidth = new javax.swing.JTextField();
        resulthight = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        s1 = new javax.swing.JLabel();
        s2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));
        jPanel1.setMaximumSize(new java.awt.Dimension(530, 550));
        jPanel1.setMinimumSize(new java.awt.Dimension(530, 550));
        jPanel1.setPreferredSize(new java.awt.Dimension(530, 550));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel13.setBackground(new java.awt.Color(255, 255, 255));
        jLabel13.setFont(new java.awt.Font("Arial", 1, 30)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel13.setText("الناتج");
        jPanel1.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 120, 90, -1));

        save1.setBackground(new java.awt.Color(98, 113, 146));
        save1.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        save1.setForeground(new java.awt.Color(255, 255, 255));
        save1.setText("تفريغ");
        save1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                save1ActionPerformed(evt);
            }
        });
        jPanel1.add(save1, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 200, 90, 40));

        total.setEditable(false);
        total.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        total.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jPanel1.add(total, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 120, 90, 30));

        jLabel10.setBackground(new java.awt.Color(255, 255, 255));
        jLabel10.setFont(new java.awt.Font("Arial", 1, 30)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel10.setText("المطلوب");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 80, 90, -1));

        jLabel14.setBackground(new java.awt.Color(255, 255, 255));
        jLabel14.setFont(new java.awt.Font("Arial", 1, 30)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel14.setText("التهدير");
        jPanel1.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 160, 90, -1));

        thderhight.setEditable(false);
        thderhight.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        thderhight.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jPanel1.add(thderhight, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 160, 60, 30));

        thderwidth.setEditable(false);
        thderwidth.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        thderwidth.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jPanel1.add(thderwidth, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 160, 60, 30));

        jLabel12.setBackground(new java.awt.Color(255, 255, 255));
        jLabel12.setFont(new java.awt.Font("Arial", 1, 30)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel12.setText("كلي");
        jPanel1.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 40, 60, -1));

        jLabel9.setBackground(new java.awt.Color(255, 255, 255));
        jLabel9.setFont(new java.awt.Font("Arial", 1, 30)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setText("طول");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 0, 60, -1));

        jLabel11.setBackground(new java.awt.Color(255, 255, 255));
        jLabel11.setFont(new java.awt.Font("Arial", 1, 30)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel11.setText("عرض");
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 0, 70, -1));

        wantedhight.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        wantedhight.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jPanel1.add(wantedhight, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 80, 60, 30));

        wantedwidth.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        wantedwidth.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jPanel1.add(wantedwidth, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 80, 60, 30));

        resultwidth.setEditable(false);
        resultwidth.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        resultwidth.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jPanel1.add(resultwidth, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 120, 60, 30));

        save.setBackground(new java.awt.Color(98, 113, 146));
        save.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        save.setForeground(new java.awt.Color(255, 255, 255));
        save.setText("حساب");
        save.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveActionPerformed(evt);
            }
        });
        jPanel1.add(save, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 50, 90, 40));

        allhight.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        allhight.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jPanel1.add(allhight, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 40, 60, 30));

        allwidth.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        allwidth.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jPanel1.add(allwidth, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 40, 60, 30));

        resulthight.setEditable(false);
        resulthight.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        resulthight.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jPanel1.add(resulthight, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 120, 60, 30));

        jLabel1.setBackground(new java.awt.Color(0, 0, 0));
        jLabel1.setMaximumSize(new java.awt.Dimension(530, 550));
        jLabel1.setMinimumSize(new java.awt.Dimension(530, 550));
        jLabel1.setPreferredSize(new java.awt.Dimension(530, 550));
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 460, 260));

        s1.setBackground(new java.awt.Color(255, 255, 255));
        s1.setFont(new java.awt.Font("Arial", 1, 30)); // NOI18N
        s1.setForeground(new java.awt.Color(255, 255, 255));
        s1.setText("/");
        jPanel1.add(s1, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 170, 10, -1));

        s2.setBackground(new java.awt.Color(255, 255, 255));
        s2.setFont(new java.awt.Font("Arial", 1, 30)); // NOI18N
        s2.setForeground(new java.awt.Color(255, 255, 255));
        s2.setText("/");
        jPanel1.add(s2, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 170, 10, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 458, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 261, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        setSize(new java.awt.Dimension(474, 300));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void saveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveActionPerformed

        
        try {
            float allwidthh=Float.parseFloat(allwidth.getText());
            float allhightt=Float.parseFloat(allhight.getText());
            float wantedwidthh=Float.parseFloat(wantedwidth.getText());
            float wantedhightt=Float.parseFloat(wantedhight.getText());
            float xremaining = allwidthh % wantedwidthh;
            float resultwidthh=(allwidthh-xremaining)/wantedwidthh;
            float yremaining = allhightt % wantedhightt;
            float resulthightt=(allhightt-yremaining)/wantedhightt;
            resulthight.setText(""+resulthightt);
            resultwidth.setText(""+resultwidthh);
            thderhight.setText(""+yremaining);
            thderwidth.setText(""+xremaining);
            total.setText(""+(Float.parseFloat(resulthight.getText()) * Float.parseFloat(resultwidth.getText())));
           // resultwidth.setText(""+());

         
        } finally {
        }


    }//GEN-LAST:event_saveActionPerformed

    private void save1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_save1ActionPerformed
       allhight.setText("");
       allwidth.setText("");
       wantedhight.setText("");
       wantedwidth.setText("");
       resultwidth.setText("");
       resulthight.setText("");
       thderhight.setText("");
       thderwidth.setText("");
       total.setText("");
       
    }//GEN-LAST:event_save1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LoginForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LoginForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LoginForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LoginForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LoginForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JTextField allhight;
    public javax.swing.JTextField allwidth;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    public javax.swing.JTextField resulthight;
    public javax.swing.JTextField resultwidth;
    private javax.swing.JLabel s1;
    private javax.swing.JLabel s2;
    private javax.swing.JButton save;
    private javax.swing.JButton save1;
    public javax.swing.JTextField thderhight;
    public javax.swing.JTextField thderwidth;
    public javax.swing.JTextField total;
    public javax.swing.JTextField wantedhight;
    public javax.swing.JTextField wantedwidth;
    // End of variables declaration//GEN-END:variables

}
